# Generated by Django 4.1 on 2022-11-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0002_delete_slackmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArithmeticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('operation_type', models.CharField(choices=[('addition', 'Addition'), ('multiplication', 'Multiplication'), ('subtraction', 'Subtraction')], max_length=255)),
            ],
        ),
    ]
