# Generated by Django 4.1 on 2022-11-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arithmeticmodel',
            old_name='a',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='arithmeticmodel',
            old_name='b',
            new_name='y',
        ),
    ]
